// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLCF2sDr6gT0s12atWMJzFrAGvoZKas2U',
    appId: '1:775426872828:web:ed0fac9480bf65e2b60e79',
    messagingSenderId: '775426872828',
    projectId: 'sportify010101',
    authDomain: 'sportify010101.firebaseapp.com',
    storageBucket: 'sportify010101.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa4FEcF0O6JaxwD3JPrxpCjPX-kwY0JB8',
    appId: '1:775426872828:android:a5f08b10fd494384b60e79',
    messagingSenderId: '775426872828',
    projectId: 'sportify010101',
    storageBucket: 'sportify010101.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpLmr5j_h-kQaH8UkfqWTGXT2kGHbrGlQ',
    appId: '1:775426872828:ios:efeb6ea79d61ca7ab60e79',
    messagingSenderId: '775426872828',
    projectId: 'sportify010101',
    storageBucket: 'sportify010101.appspot.com',
    iosBundleId: 'com.example.spotifyApplicationClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpLmr5j_h-kQaH8UkfqWTGXT2kGHbrGlQ',
    appId: '1:775426872828:ios:efeb6ea79d61ca7ab60e79',
    messagingSenderId: '775426872828',
    projectId: 'sportify010101',
    storageBucket: 'sportify010101.appspot.com',
    iosBundleId: 'com.example.spotifyApplicationClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLCF2sDr6gT0s12atWMJzFrAGvoZKas2U',
    appId: '1:775426872828:web:23b4392f1778f980b60e79',
    messagingSenderId: '775426872828',
    projectId: 'sportify010101',
    authDomain: 'sportify010101.firebaseapp.com',
    storageBucket: 'sportify010101.appspot.com',
  );
}
